# -*- coding: utf-8 -*-
"""mathReto6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOlzpoRjmaSlMmVp8YLiK1HKx1HzEshT
"""

print("1. a")
import numpy as np
import matplotlib.pyplot as plt

# Generar los puntos para el gráfico
x = np.linspace(-10, 10, 1000)  # Ajustar el rango de valores de x y aumentar la resolución

# Evaluar la función exponencial directamente en los valores de x
y = 1000*(np.exp(0.2*x))

# Graficar la función
plt.plot(x, y)
plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
plt.xlabel('x')
plt.ylabel('y')
plt.title('Gráfico de la función $e^x$')
plt.grid(True)
plt.show()

print("1. b")
print(1000*(np.exp(5*0.2)))

print("2. ")
import numpy as np
import matplotlib.pyplot as plt

# Generar los puntos para el gráfico
x = np.linspace(10, 13, 1000)  # Ajustar el rango de valores de x y aumentar la resolución

# Evaluar la función exponencial directamente en los valores de x
y = 1000*(np.exp(0.2*x))

# Graficar la función
plt.plot(x, y)
plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
plt.xlabel('x')
plt.ylabel('y')
plt.title('Gráfico de la función $e^x$')
plt.grid(True)
plt.show()

print("Aproximando con la grafica, se llegara a 10000 celulas cancerigenas en 11.5 dias. Comprobacion de el despeje en fisico.")
print("Valor exacto con el despeje fisico: ", ((np.log(10))/0.2))
print("""2. b. Las limitaciones de la grafica al aproximar a situaciones reales es que esta no discrimina. No toma factores
      externos como puede ser la alimentacion del paciente, sus habitos, su edad, su contextura, otras condiciones presentes
      o las predisposiciones geneticas de este. La exponencial ademas, va hasta valores infinitos, cosa imposible en un escenario real.""")

print("3.")
import numpy as np
import matplotlib.pyplot as plt


def grafica1():#Funcion para que lo que le haga a esta grafica no afecte a la otra
  x = np.linspace(-10, 10, 1000)

  # Evaluar la función exponencial directamente en los valores de x
  y = 1000*(np.exp(0.2*x))

  # Graficar la función
  plt.plot(x, y)
  plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
  plt.xlabel('x')
  plt.ylabel('y')
  plt.title('Gráfico de la función mas simple')
  plt.grid(True)
  plt.show()
  return
grafica1()

def grafica2():#Funcion para que lo que le haga a esta grafica no afecte a la otra
  x = np.linspace(-10, 10, 1000)

  # Evaluar la función exponencial directamente en los valores de x
  y = (1000*5000)/(1000+(5000-1000)*(np.exp(-0.2*x)))

  # Graficar la función
  plt.plot(x, y)
  plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
  plt.xlabel('x')
  plt.ylabel('y')
  plt.title('Gráfico de la función mas especifica')
  plt.grid(True)
  plt.show()
  return
grafica2()

print("""La más especifica tiene un crecimiento mas reducido, pues toma mas aspectos que afectarian al crecimiento en la vida real,
      por esto, digo que es más acertada que la grafica simple, aunque no se vean unos resultados más pronunciados.""")

print("4. ")
print("Valor de r despejado en fisico: ", (np.log(12.3)))
R=(np.log(12.3))

def grafica3():#Funcion para que lo que le haga a esta grafica no afecte a la otra
  x = np.linspace(-10, 10, 1000)
  R=(np.log(12.3))

  # Evaluar la función exponencial directamente en los valores de x
  y = 10*(np.exp(2.5*x))

  # Graficar la función
  plt.plot(x, y)
  plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
  plt.xlabel('x')
  plt.ylabel('y')
  plt.title('Gráfico del modelo mas simple')
  plt.grid(True)
  plt.show()
  return
grafica3()

def grafica4():#Funcion para que lo que le haga a esta grafica no afecte a la otra
  x = np.linspace(-10, 10, 1000)
  R=(np.log(12.3))

  # Evaluar la función exponencial directamente en los valores de x
  y = (10*5000)/(10+(5000-10)*(np.exp(-2.5*x)))

  # Graficar la función
  plt.plot(x, y)
  plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
  plt.xlabel('x')
  plt.ylabel('y')
  plt.title('Gráfico del modelo mas especifico')
  plt.grid(True)
  plt.show()
  return
grafica4()
print("""Cuando ambas tienden a infinito negativo, el comportamiento es parecido, ambas tienden a la asintota y=0 sin nunca llegar a ella,
      tambien experimentan un comportamiento parecido en el intervalo [0 , 2.5] pues ambas toman un comportamiento exponencial, pero frena
      en el modelo elaborado debido a sus limitaciones.""")