# -*- coding: utf-8 -*-
"""Math_Ardillas_David_Gutierrez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OQ9ihLmRPuuvH75uMYQdvWgqzQWdc5--

Reto 1

 Dinámica de reproducción de las ardillas

También se está investigando el comportamiento de la población de ardillas rojas. Se ha inferido la siguiente información sobre la población actual de ardillas en las zonas bajo estudio:

• Ardillas adultas (1 año o más): 6810.

• Ardillas juveniles (26 a 52 semanas): 2470.

• Ardillas crías (0 a 26 semanas): 3090.

Adicionalmente, se ha encontrado la siguiente información sobre la especie:

• Proporción de género: la proporción de machos a hembras es de uno a uno en todas las

clases de edades (es decir, hay igual número de machos y hembras en cada grupo de edad).

• Ciclo reproductivo: un ciclo reproductivo dura 26 semanas. Cada hembra adulta tiene dos

crías por ciclo reproductivo.

• Supervivencia en el siguiente ciclo reproductivo:

• De las 3090 crías, 618 sobrevivieron y pasan a ser juveniles.

• De las 2470 ardillas juveniles, 1729 sobrevivieron y pasan a ser adultas.

• De las 6810 ardillas adultas, 5448 sobrevivieron.

Con base en la información anterior y las herramientas computacionales brindadas por el lenguaje de programación Python, responda las siguientes preguntas.

1. ¿Cuál es el porcentaje de supervivencia en cada grupo de edad?

2. ¿Cuál es la población total de ardillas después del primer ciclo reproductivo?

3. ¿Cuál es la población total de ardillas después de cinco ciclos reproductivos?

4. Con base en las respuestas a las preguntas anteriores, ¿podría argumentar que la población de ardillas aumentaría, disminuiría o se mantendría estable después de varios ciclos reproductivos?

5. Si el objetivo es mantener estable la población de ardillas en las zonas verdes bajo estudio, ¿qué acciones podrían sugerir los biólogos a la administración municipal para este fin? Explique qué entiende por “mantener estable”.

6. Con base en las proporciones inferidas, ¿cuál debió ser la población de ardillas, por grupo,

antes del ciclo reproductivo que dio lugar a la población inicialmente
"""

#Pregunta 1
print("Porcentaje de supervivencia crias " + str(618*100/3090))
print("Porcentaje de supervivencia juveniles " + str(1729*100/2470))
print("Porcentaje de supervivencia adultas " + str(5448*100/6810))

#Pregunta 2
print("Ardillas adultas " + str(1729+5448))
print("Ardillas bebe " + str(5448/2*2))
print("Ardillas juveniles 618")
print("Ardillas totales " + str(7177+5448+618))

#Pregunta 3
print("año 2")
print("Ardillas adultas " + str(7177*0.8+618*0.7))
print("Ardillas bebe " + str(7177))
print("Ardillas juveniles " + str(5448*0.2))
print("Ardillas totales " + str(6174+7177+1090))
print("año 3")
print("Ardillas adultas " + str(6174.2*0.8+1089.6*0.7))
print("Ardillas bebe " + str(6174.2))
print("Ardillas juveniles " + str(7177*0.2))
print("Ardillas totales " + str(5702.1+6174.2+1435.4))
print("año 4")
print("Ardillas adultas " + str(5702.1*0.8+1435.4*0.7))
print("Ardillas bebe " + str(5702.1))
print("Ardillas juveniles " + str(6174.2*0.2))
print("Ardillas totales " + str(5566.46+5702.1+1234.84))
print("año 5")
print("Ardillas adultas " + str(5566.46*0.8+1234.84*0.7))
print("Ardillas bebe " + str(5566.46))
print("Ardillas juveniles " + str(5702.1*0.2))
print("Ardillas totales " + str(5317.56+5566.46+1140.42))

#Pregunta 4
print("La población de ardillas disminuye al transcurrir los primero años, sin embargo, esta disminucion cada año es mas pequeña, si tomamos mas instancia de tiempo el numero de ardillas se mantendra constante")

#Pregunta 5
print("Por la naturaleza que demuestra la reduccion de ardillas anualmente, la poblacion se va a mantener constante si los años pasan y las condiciones iniciales de natalidad y mortanilidad son las mismas")

#Pregunta 6
print("Las aridllas deberian ser un poco menores a las del año 5, pues ya casi se alcanza el balance, algo como:")
print("Ardillas adultas 5052.34")
print("Ardillas bebe 5317.56")
print("Ardillas juveniles 1113.29")