# -*- coding: utf-8 -*-
"""Math_Reto5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-Q3pOsU8tJi2dVicK2uoG3lx1zi1wt3
"""

#1. A
from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(((60*x**2-x**3)/16000)-1, 0)

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la solución de la ecuación es:",solucion)

#1. B
from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(((60*x**2-x**3)/16000)-0.1215, 0)

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la solución de la ecuación es:",solucion)

#2
print("2.")
import numpy as np
import matplotlib.pyplot as plt

# Generar los puntos para el gráfico
x = np.linspace( 0, 200, 1000)  # Ajustar el rango de valores de x y aumentar la resolución

# Evaluar la función polinomial directamente en los valores de x
y = (60*x**2-x**3)/16000

# Graficar la función
plt.plot(x, y)
plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
plt.xlabel('x')
plt.ylabel('y')
plt.title('Gráfico de la función polinomial')
plt.grid(True)
plt.show()

#deflexion en x=50
a=(60*50**2-50**3)/16000
print("deflexion en x=50:",a)

#deflexion en x=70
b=(60*70**2-70**3)/16000
print("deflexion en x=70:",b)
#3
print("3.")
#Minima deflexion en x=200:
c=(60*200**2-200**3)/16000
print("deflexion minima en x=200:",c)
#Maxima deflexion aproximada a x=40
d=(60*40**2-40**3)/16000
print("deflexion maxima en x=40:",d)

#4
from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(((60*x**2-x**3)/16000), 0)

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la solución de la ecuación es:",solucion)
print("En el intervalo [50,70], solo nos sirve la solucion 60")
print("Esto SI coincide con la grafica")
import numpy as np
import matplotlib.pyplot as plt

# Generar los puntos para el gráfico
x = np.linspace( 50, 70, 1000)  # Ajustar el rango de valores de x y aumentar la resolución

# Evaluar la función polinomial directamente en los valores de x
y = (60*x**2-x**3)/16000

# Graficar la función
plt.plot(x, y)
plt.axhline(0, color='black', linewidth=0.5)  # Agregar una línea en y=0
plt.xlabel('x')
plt.ylabel('y')
plt.title('Gráfico de la función polinomial')
plt.grid(True)
plt.show()

a=(60*50**2-50**3)/16000
print("""5.
  el punto maximo es igual a:""", a)
b=(60*70**2-70**3)/16000
print("El punto minimo es",b)
#saco la mitad
c=((a+b*-1)/2)-3.0625
print("La mitad es",c)

from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(((60*x**2-x**3)/16000)+0.75, 0)

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la mitad de el segmento de grafico es:",solucion)