# -*- coding: utf-8 -*-
"""Math_Reto2_Completo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajndBlc7BiB2A8YwwD5c6vXvKhvbQSSl
"""

print("#1")
#1
print("1. Para despejar el area superficial, necesito el radio, como solo tengo el volumen, uso la formula del volumen para despejar el radio")
#despejar el radio
import sympy as sp
r=(30/(4*3.14))**(1/3)
print("El radio es ", r)
#2
print("#2")
print("2. Uso el radio para sacar el area")
area=(4*3.14*(r**2))
print("El area es ", area)
#3
print("#3")
print("El diametro es el doble del radio")
diametro=2*r
print("El diametro es ", diametro)
#4
print("#4")
Altura_cilidro=(10/(3.14*(r**2)))
print("La altura del cilindro es ", Altura_cilidro)
Area_cilindro=2*3.14*r*(r+Altura_cilidro)
print("El area del cilindro es ", Area_cilindro)
#4.5 Calculos para el area
print("#4.5")
print("Para reducir el costo hay que reducir el material, este material es igual al area superficial del contenedor. Menos area=Menos costo")
print("No se puede reducir el area de una esfera sin perder volumen, hay que cambiar de forma.")
print("En el caso de el cilindro si se puede")
#prueba 1, mayor radio, menor altura.
H=(10/(3.14*(2**2)))
print("La altura del cilindro es ", H)
A=2*3.14*2*(2+H)
print("El area del cilindro es ", A, "aumento por lo tanto no sirve")
#prueba 2, menor radio, mayor altura
H2=(10/(3.14*(1.1**2)))
print("La altura del cilindro es ", H2)
A2=2*3.14*1*(1+H2)
print("El area del cilindro es ", A2, ", disminuyo por lo tanto si sirve, para reducir costos se debe reducir el radio y aumentar altura")