# -*- coding: utf-8 -*-
"""Math_Reto4_Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBgOjHtWMAiDfxgX4nz00M9kkCoJ-Lis
"""

#1.
import numpy as np
import matplotlib.pyplot as plt

# Generar valores de x
x = np.linspace(-100, 100, 400)

# Evaluar la función cuadrática directamente
y = -0.001*(x**2) + 0*x + 10

# Graficar
plt.plot(x, y, label='$f(x) = -0.001*(x**2) + 0*x + 10$')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('Gráfica de la función cuadrática')
plt.legend()
plt.grid(True)
plt.show()
#Respuesta: B no puede ser positivo para tener sentido fisico, pues al ser positivo, el material se repararia con el tiempo a pesar del deterioro quimico, empezando en la nada al año 0, pero si puede ser 0 o negativo.

#2
print("2.")
A= 0.001*2**2 + -0.1*2 + 10
print("El diametro es", A, "cm")
#3
print("3.")
import sympy as sp

# Definir la variable
x = sp.symbols('x', real=True)

# Definir la inecuación
inequality = -0.001*x**2-0.1*x < -9

# Resolver la inecuación
solution = sp.solve_univariate_inequality(inequality, x, relational=False)


# Mostrar la solución
print("Solución sin relacional:", solution)
print("Desde los 57.238 años, el protector se considera inutilizable.")

#4
import numpy as np
import matplotlib.pyplot as plt

# Generar valores de x
x = np.linspace(9, 10, 400)

# Evaluar la función cuadrática directamente
y = -100*(x**2) + 1950*x - 8100

# Graficar
plt.plot(x, y, label='$f(x) = -0.001*(x**2) + 0*x + 10$')
plt.xlabel('x')
plt.ylabel('f(x)')
plt.title('Gráfica de la función cuadrática')
plt.legend()
plt.grid(True)
plt.show()
#El maximo coste de mantenimiento ocurre en el vertice de la parabola, cuando el diametro es de 9.75, el minimo coste es cuando el cable tiene un diametro de 9, al final de la grafica parcializada por el caso.

# 5 Hay que reducir a hasta el nivel más cercano a 0 posible pero sin llegar a este, pues este
# corresponde a la corrocion y mientras menos de esta haya, mas tardara en dañar el cable. En el caso de B, hay que acercarlo lo mas posible a 0 sin llegar a ser positivo pues no tendria sentido fisico.
print("Comparacion con un tiempo de 2 años en 2 casos")
print("Acercandolos a 0")
A= 0.0001*2**2 + -0.01*2 + 10
print("El diametro es", A, "cm")
print("Alejandolo de 0")
B= 0.01*2**2 + -0.1*2 + 10
print("El diametro es", B, "cm")
print("Se desgasto mas el que los datos se alejaron de 0")