# -*- coding: utf-8 -*-
"""math_Reto3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlmo2P6ZTfTeXUbdkaozSSk6blVM2L9Y
"""

#1.
from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(150000+50*x**2, 300000)

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la solución de la primera ecuacion es:",solucion) #El tiempo no es negativo
print("Lo que significa que la solucion es 3000 ")

#2.
from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(90*x**2, 20000)

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la solución de la primera ecuacion es:",solucion) #El tiempo no es negativo
h=(20000/90)**(1/2)
print("Lo que significa que la solucion es ",h)

#3
import sympy as sp

# Definir la variable
x = sp.symbols('x', real=True)

# Definir la inecuación
inequality = 20000<50*x**2

# Resolver la inecuación
solution = sp.solve_univariate_inequality(inequality, x, relational=False)


# Mostrar la solución
print("Solución sin relacional:", solution) #El tiempo no puede ser negativo
q=(20000/50)**(1/2)
print("Lo que significa que despues del mes",q)

#4
import sympy as sp

# Definir la variable
x = sp.symbols('x', real=True)

# Definir la inecuación
inequality = 20000<90*x**2

# Resolver la inecuación
solution = sp.solve_univariate_inequality(inequality, x, relational=False)


# Mostrar la solución
print("Solución sin relacional:", solution) #El tiempo no puede ser negativo
q=(20000/90)**(1/2)
print("Lo que significa que despues del mes",q, " y en adelante, seran mayores los costos.")

5#
import sympy as sp

# Definir la variable
x = sp.symbols('x', real=True)

# Definir la inecuación
inequality = 20000*x-(100000+90*x**2+10*x)>=20000*x-(150000+50*x**2+10*x)

# Resolver la inecuación
solution = sp.solve_univariate_inequality(inequality, x, relational=False)

# Mostrar la solución
print("Solución sin relacional:", solution) #El tiempo no puede ser negativo
print("Desde el primer mes hasta el 35.355 que sus costos totales superaran al de la B")

#6
from sympy import Symbol, Eq, solve

x = Symbol('x', real=True)

ecuacion = Eq(x*20**2, 150000+50*20**2+10*20) #Hay varias formas de interpretar

print("Resolviendo la ecuación")
display(ecuacion)
solucion = solve(ecuacion)

print("la solución de la primera ecuacion es:",solucion) #El tiempo no es negativo
h=(851/2)
print("Lo que significa que la solucion es ",h)