# -*- coding: utf-8 -*-
"""python_TicTac_MiniProyecto2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXy0MvGmDuocI89LtAf5qAHS8w0SL6kA
"""

import pygame
def iniciador():
    global Pantalla, Fondo, Circ, Equis, Tablero
    pygame.init
    Pantalla=pygame.display.set_mode((450,450)) #Carga y "Configura" como se deberia cargar el programa y sus dimensiones
    pygame.display.set_caption("Tic Tac de David") #El nombre que va a llevar el programa al ejecutar

    Fondo=pygame.image.load("Recursos/Tablero.png") #Le doy una variable a cada imagen para usarlas luego
    Circ=pygame.image.load("Recursos/O.png")
    Equis=pygame.image.load("Recursos/X.png")

    Fondo=pygame.transform.scale(Fondo,(450,450)) #Defino con que dimensiones cargar la imagen
    Circ=pygame.transform.scale(Circ,(125,125))
    Equis=pygame.transform.scale(Equis,(125,125))


    Tablero = [["","",""],
        ["","",""],
        ["","",""]]
    return

iniciador()

def Gequis(fila,colum):

    Pantalla.blit(Equis, Coord[fila][colum])#Graficara una X en las cordenadas dadas

def Gcirc(fila,colum):

    Pantalla.blit(Circ, Coord[fila][colum])#Graficara un O en las cordenadas dadas




def Graficador():
    global Coord, Tablero, fila, colum

    Coord= [[(40,50),(165,50),(290,50)],
        [(40,175),(165,175),(290,175)],
        [(40,300),(165,300),(290,300)]]#3 listas de listas para hacer una matriz




    Pantalla.blit(Fondo, (0,0))#Defino la posicion donde ahora si mostrar cada imagen
    for fila in range(3):
        for colum in range(3):#For para recorrer la matriz
            if Tablero[fila][colum] == "X":
                Gequis(fila,colum)
            elif Tablero[fila][colum] == "O":
                Gcirc(fila,colum)

def Verificador():
    for i in range(3):
        if Tablero[i][0] == Tablero[i][1] == Tablero[i][2] != "": #verifica si hay 3 iguales horizontales, i para que sea la misma fila, 1,2,3 para cada colum
            print("El jugador ",Turno," ha ganado")
            return True
        if Tablero[0][i] == Tablero[1][i] == Tablero[2][i] != "": #verifica si hay 3 iguales verticales, i para que sea la misma fila, 1,2,3 para cada colum
            print("El jugador ",Turno," ha ganado")
            return True
    if Tablero[0][0] == Tablero[1][1] == Tablero[2][2] != "": #verifica si hay 3 iguales diagonales derecha, i para que sea la misma fila, 1,2,3 para cada colum
        print("El jugador ",Turno," ha ganado")
        return True
    if Tablero[0][2] == Tablero[1][1] == Tablero[2][0] != "": #verifica si hay 3 iguales diagonales izquierda, i para que sea la misma fila, 1,2,3 para cada colum
        print("El jugador ",Turno," ha ganado")
        return True
    if Tablero[0][0] and Tablero[0][1] and Tablero[0][2] and Tablero[1][0] and Tablero[1][1] and Tablero[1][2] and Tablero[2][0] and Tablero[2][1] and Tablero[2][2] != "":
        print("Empate!")
        return True
    return False




def Jujar():
    global Turno, Fin, Frames, fila, colum
    Turno= "X"
    Fin = False
    Frames= pygame.time.Clock()
    Cerrar = False


    while not Cerrar:
        Frames.tick(30) #Define que el juego corre a 30fps y procese los eventos como un click.

        for event in pygame.event.get():#Captura todos los eventos que sucedan durante un mismo frame y los para analizar por orden
            if event.type == pygame.QUIT:
                Cerrar=True
            if Fin==True:
                if event.type == pygame.KEYDOWN:
                    iniciador()
                    Turno="X"
                    Fin==False



            elif event.type == pygame.MOUSEBUTTONDOWN:#Defino que pasa si le doy click
                mouseX, mouseY = event.pos #Saco las coordenadas del mouse justo luego de clickear
                if (mouseX >= 40 and mouseX < 415) and (mouseY >= 50 and mouseY < 415): #Solo me importan las coordenadas cercanas a una posicion
                    fila=(mouseY - 50)//125 #50 pues el tablero como tal inicia despues, 125 pues cada posicion mide ancho 125px
                    colum=(mouseX - 40)//125
                    #print(fila,colum)
                    if Tablero[fila][colum] == "":#Solo si la posicion esta vacia
                        Tablero[fila][colum] = Turno #cambio a la X o O dependiendo
                        Fin=Verificador()
                        if Fin==True:
                            if event.type == pygame.K_r:
                                iniciador()
                                Turno="X"

                        Turno = "O" if Turno == "X" else "X"
                        #print(Turno)

        Graficador()

        pygame.display.update() #Actualizo mi programa

    pygame.quit()

Jujar()