# -*- coding: utf-8 -*-
"""inputLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SGm92fRhKgcyulzw3Bw50GlyHZS1ozou
"""

horas = float(input("numero de horas trabajadas: "))
valor_hora = float(input("valor de hora trabajada: "))
print("salario =" + str(horas * valor_hora))

n=int(input("ingrese el entero positivo: "))
suma=(n*(n+1))/2
print("la suma de los primeros numeros enteros positivos es: " + str(suma))

peso = float(input("peso en kg: "))
estatura = float(input("estatura en metros: "))
imc = peso/(estatura**2)
print("imc = " + str(imc))
a = round(imc,2)
print("tu peso es " + str(a))

N = float(input("Dame un numero: "))
M = float(input("Dame otro numero: "))
print((N/M))
print("C =" + str(N/M))
print("R =" + str(N%M))