# -*- coding: utf-8 -*-
"""pythonExam1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GIP7wAdigmHibjYF-hWUIIv-iRh2TYnh
"""

#1.
def sumador():
  Lista=[1,2,3,10]
  a=0
  for i in Lista:
    a+=i
  return a

sumador()

#2.
def maximizador():
  Lista=[1,20,300,10]
  a=Lista[0]#empiezo con el primer numero de la lista
  for i in Lista:
    if i>a:
      a=i
  return a

maximizador()

#3.
def promediador():
  Lista=[3,4,5,0]
  a=0
  for i in Lista:
    a+=i#sumo todos
  return a/len(Lista)#se divide con el numero de digitos de la lista

promediador()

#4.
def pareador():
  Lista=[1,2,3,4,5,6,7,8,9,10]
  Pares=[]
  for i in Lista:
    if i%2==0: #Si el residuo de la div por 2 es 0
      Pares.append(i)#Lo añado a mi nueva lista
  return Pares

pareador()

#5.
def Cuentador():
  Lista=[1,1,3,4,5,6,7,8,9,1]
  Elm=1
  Cuenta=0

  for i in Lista:
    if Elm==i:
      Cuenta+=1
  return Cuenta

Cuentador()

#6.
def Volteador():
  Lista=[1,2,3,4,5]
  atsiL=[]
  Lista.reverse()#Una funcion exclusiva de las listas que invierte el orden de los elementos
  for i in Lista:
    atsiL.append(i)#Meto cada elemento en la nueva lista
  return atsiL
Volteador()

#7.
def Duplicador():
  Lista=[1,2,3,4,5]
  Dupli=[]
  for i in Lista:
    Dupli.append(i)
    Dupli.append(i)#Se añade el mismo elemento 2 veces al tiempo para mantener el orden
  return Dupli
Duplicador()

#8.
def Desduplicador():
  Lista=[1, 1, 2, 2, 3, 3, 4, 4, 5, 5]
  Desduplicado=[]
  for i in Lista:
    if i in Desduplicado:
      a=0#Algo que no hace nada para que siga la funcion.
    else:
      Desduplicado.append(i)
  return Desduplicado
Desduplicador()

#9
def Cuenta():
  Dic={}
  a=input("Intruduzca una palabra: ")
  Ba=a[::1]#Un comando que corta un string, el 1 es para que mantenga el orden original, la primera seccion es donde inicia, la segunda, hasta cuando va
  for i in Ba:
    Clave=i
    if Clave in Dic:
      Dic[Clave]+=1
    else:
      Dic[Clave]=1
  return Dic
Cuenta()

#10
def DiccioRaro():
  Dic={'H': 1, 'o': 1, 'l': 1, 'a': 3, ' ': 1, 'm': 2}
  ciD={}
  for Clave, Valor in Dic.items(): #Llama el valor y la clave dentro de los elementos de el diccionario al tiempo
    ciD[Valor]=Clave #Cambia el valor por la clave
  return ciD
DiccioRaro()

#11
def Buscaclaves():
  B={'H': 1, 'o': 1, 'l': 1, 'a': 3, ' ': 1, 'm': 2}
  a=input("Intruduzca una la clave: ")
  if a in B:
    return True
  else:
    return False
Buscaclaves()

#12
def Valorizador():
  Dic={'H': 1, 'o': 1, 'l': 1, 'a': 3, ' ': 1, 'm': 2}
  Encontrado=[]
  a=1
  for Clave, Valor in Dic.items(): #Llama a la clave y el valor dentro de los elementos en general del diccionario
    if Valor==a:
      Encontrado.append(Clave)
  return Encontrado
Valorizador()

#13

#14
def Sumaedad():
  Dic={'Halfonso': 10, 'orfeo': 34, 'lisa': 12, 'andres': 31, 'Juan': 1, 'manuela': 20}
  Suma=0
  for i in Dic:
    Suma+=Dic[i]
  return Suma
Sumaedad()

#15
def Valorizador():
  Dic={'H': 1, 'o': 1, 'l': 1, 'a': 3, ' ': 1, 'm': 2}
  Duplica={}
  a=1
  for Clave, Valor in Dic.items():
    Duplica[Clave]=Valor*2
  return Duplica
Valorizador()

#16
def Discriminador():
  Dic={'H': 1, 'o': 1, 'l': 1, 'a': 3, ' ': 1, 'm': 2}
  Saca=["H","o","l"]
  Dic2={}
  for Clave, Valor in Dic.items():
    if Clave in Saca:
      a=0
    else:
      Dic2[Clave]=Valor
  return Dic2
Discriminador()