# -*- coding: utf-8 -*-
"""pythonAlgoritmos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yL4--KP7N7UqPSZMPV2CFGqTtCU5e4kk
"""

a=int(input("numero de horas trabajadas "))
b=float(input("costo por hora "))
if(a<47):
  print("su sueldo es",a*b)
else:
  print("su sueldo es",a*b*1.1)
print("fin del programa")

a=float(input("ingrese el peso: "))
b=float(input("ingrese la altura: "))
imc=round(a/(b*b),1)
print("su imc es",imc)
if(imc<18.5):
  print("Flaco")
elif(18.5<imc<24.9):
  print("Normal")
elif(25<imc<29.9):
    print("Sobrepeso")
else:
    print("Obesidad")

n=float(input("Numero entero positivo: "))
a=float((n*(n+1))/2)
if(a>20):
  print(a)
  print("WOW, que genial!")
else:
  print(a)

"""Pedir 2 numeros enteros N y M
dividir N y M
mostrar el cociente C y el residuo R entero
Si C es menor a 1 le adiciona el mensaje "Divisor mayor al dividendo" de lo contrario "Divisor menor al dividendo". Si en igual a 1 pues es igual bro.
"""

N=int(input("ingrese numero entero: "))
M=int(input("ingrese numero entero: "))
print(N, "/", M, "=", N/M)
C=N/M
print(N, "%", M, "=", N%M)
if(C<1):
  print("Divisor mayor al dividendo")
elif(C>1):
  print("Divisor menor al dividendo")
elif(C==1):
  print("Divisor igual al dividendo")

""">Preguntar por una cantidad a invertir, el numero de años y un interes anual
si el capital es menor a 100000, muestre el mensaje "Baja rentabilidad".
si el capital esta entre 100000 y 1000000, muestre el mensaje "rentabilidad moderada".
si el capital es mayor a 1000000 muestre el mensaje "Alta rentabilidad."

"""

B=int(input("ingrese la cantidad a invertir: "))
A=int(input("ingrese el numero de años: "))
C=float(input("ingrese el interes anual: "))
print(B*((C/100)+1)**A)
if(B<100000):
  print("Baja rentabilidad")
elif(100000<B<1000000):
  print("rentabilidad moderada")
else:
  print("Alta rentabilidad")

"""Preguntar por el numero de payasos y muñecas que hay en la caja y multiplicar por 0.112 y 0.075 respectivamente. Por ultimo, sumar el total.
Si la suma es mayor a 3000, preguntar si quiere enviar o no, en caso que si, colocar, contenedor enviado, de lo contrario "contenedor no enviado"
"""

A=int(input("ingrese el numero de payasos: "))
B=int(input("ingrese el numero de muñecas: "))
P_Payasos=A*0.112
P_Muñecas=B*0.075
Total=round(P_Payasos+P_Muñecas,2)
if(Total>3000):
  input("Desea enviar el paquete? ")
  if(str(input=="si")):
    print("Contenedor enviado")
  else:
    print("Contenedor no enviado")
else:
  print("El peso del paquete es: ", Total, "Kg")

"""Una funcion que reciba 2 numeros y retorne la suma de dichos numeros"""

def suma(a,b):
  return a+b
R=suma(5,8)
print(R)

def suma(a,b):
  return a-b
R=suma(5,8)
print(R)

def suma(a,b):
  return a*b
R=suma(5,8)
print(R)

def suma(a,b):
  if(b==0):
    return "No se puede dividir entre 0"
  else:
    return a/b
R=suma(5,0)
print(R)

def suma(a,b):
  a=input("Signo operacion: ")
  if a=="+":
    return a+b
  elif a=="-":
    return a+b
  elif a=="*":
    return a*b
  elif a=="/":
    if(b==0):
      return "No se puede dividir entre 0"
    else:
      return a/b
  else:
    return "No es una operacion valida"
R=suma(5,8)
print(R)

print("Calculadora super simple de 4 operaciones super basicas")
a=int(input("introduzca un entero: "))
o=input("Signo operacion: ")
b=int(input("introduzca un entero: "))
def suma(a,b):
  if o=="+":
    return a+b
  elif o=="-":
    return int(a)-b
  elif o=="*":
    return int(a)*b
  elif o=="/":
    if(b==0):
      return "No se puede dividir entre 0"
    else:
      return int(a)/b
  else:
    return "No es una operacion valida"
R=suma(a,b)
print(R)

d=int(input("Cantidad a depositar: "))
def Bank(a,b):
  if 0<d<1000000:
    return d*1.02
  elif 1000000<=d<2000000:
    return int(d)*1.05
  elif d>=2000000:
    return int(a)*b
  elif d=="/":
    if(b==0):
      return "No se puede dividir entre 0"
    else:
      return int(a)/b
  else:
    return "No es una operacion valida"

def Acuadrado():
  a=int(input("Lado del cuadrado: "))
  return a*a
  print("El area del cuadrado es: ", Acuadrado())
def Atriangulo():
  b=int(input("Base del triangulo: "))
  h=int(input("Altura del triangulo: "))
  return (b*h)/2
  print("El area del triangulo es: ", Atriangulo())
def Acirculo():
  r=int(input("Radio del circulo: "))
  return 3.1416*r*r
  print("El area del circulo es: ", Acirculo())
def Arombo():
  D=int(input("Diametro mayor del rombo: "))
  d=int(input("diametro menor del rombo: "))
  return (D*d)/2
  print("El area del rombo es: ", Arombo())
def Apentagono():
  a=int(input("Lado del apentagono: "))
  return (5*a*a)/2
  print("El area del apentagono es: ", Apentagono())
def Areasfig():
  print("Calculadora de areas de figuras geometricas")
  F=print("""Que figura desea calcular?
  1. Cuadrado
  2. Triangulo
  3. Circulo
  4. Rombo
  5. Pentagono""")
  if F=="1":
    print("El area del cuadrado es: ", Acuadrado())
  elif F=="2":
    print("El area del triangulo es: ", Atriangulo())
  elif F=="3":
    print("El area del circulo es: ", Acirculo())
  elif F=="4":
    print("El area del rombo es: ", Arombo())
  elif F=="5":
    print("El area del pentagono es: ", Apentagono())
  else:
    print("No es una figura valida")
Areasfig()
#figura.lower()

l=float(input("¿Precio? "))
M=input("¿Marca? ")
def NOSY(l,):
  l*0.95
def Plata(l):
  l*0.9
def IVA(l):
  l*1.2
def PrecioFinal():
  if M=="NOSY":
    return NOSY()
  elif P>=2000000:
    return Plata()
  else:
    return IVA()
    print(P)
    exit()
PrecioFinal()
print(P)

def menu():
  print("Calculadora super simple de 4 operaciones super basicas")
  print("""Que operacion desea realizar?
  1. +
  2. -
  3. x
  4. /
  5. Salir""")
W = True  # Initialize W to start the loop
while W == True:
    menu()
    a = int(input("introduzca un entero: "))
    o = input("Signo operacion: ")
    b = int(input("introduzca un entero: "))

    def suma(a, b):
        if o == "+":
            return a + b
        elif o == "-":
            return int(a) - b
        elif o == "*":
            return int(a) * b
        elif o == "/":
            if b == 0:
                return "No se puede dividir entre 0"
            else:
                return int(a) / b
        elif o == "Salir":
            print("Gracias por usar la calculadora")
            W = False

        else:
            return "No es una operacion valida"
            W = False
    break

    R = suma(a, b)
    print(R)

A=0
def menu():
  print("""Calculadora de compras!
    Evite introducir valores negativos
    Introduzca 0 para finalizar""")
menu()
while True:
  S=float(input("ingrese un valor "))
  if S>0:
    A+=S
  elif S==0:
    break
  else:
    print("Valor invalido")
if A>=1000000:
  A*=0.9
print("El total de la compra es: ", A)

import random
e=random.randint(1,10)
f=0
while e!=f:
  f=int(input("Adivina el numero: "))
  if f<e:
    print("El numero es mayor")
  elif f>e:
    print("El numero es menor")
  else:
    print("Adivinaste")
    break

def tablas():
  k=int(input("ingrese un numero: "))
  for c in range(1,11):
    print(k*c)
tablas()

from os import NGROUPS_MAX
def factorial():
  n=int(input("ingrese un numero: "))
  for c in range(1,n):
    h=n*c
    t=+h
    print(h)
factorial()

def factorial():
  n=int(input("ingrese un numero: "))
  f = 1
  for c in range(1,n+1):
    f *= c
  print(f)

factorial()

ABC=list(("a","b","c","d","e","f","g","h","i","j","k","l","m","n","ñ","o","p","q","r","s","t","u","v","w","x","y","z"))
for c in range(2,28,3):
  print(c)
print(ABC)

#

ABC=list(("a","b","c","d","e","f","g","h","i","j","k","l","m","n","ñ","o","p","q","r","s","t","u","v","w","x","y","z"))
CFI = []
for c in range(2,28,3):
  CFI.append(ABC[c])
for a in CFI:
  ABC.remove(a)
print(ABC)

def palindromeitor():
  Ba=input("ingrese una frase: ").replace(" ","").lower()
  a=Ba[::-1]
  if a==Ba:
    print("Es palindromo")
  else:
    print("No es palindromo")
  print(a)
palindromeitor()

a=int(input("ingrese un numero arepero: "))
b=a*2000
def Descarepa(x):
  if a<=2:
    b=x*0.98
  elif 2<a<5:
    b=x*0.95
  elif 5<=a:
    b=x*0.90
  return b
b=Descarepa(b)
print(b)

a=[50,75,46,22,80,65,8]
a.sort()
for c in range(1,len(a)-1):
  a.remove(a[1])
print(a)

def yappinton():
  a=[1,2,3]
  b=[-1,0,2]
  c=0
  for k in range(len(a)):
    c+=(b[k]*a[k])
  print(c)
yappinton()

a=0
b=0
c=0
Contactos=[]
def Agregar(Nom,Cel,Email):
  Nom=input("Nombre del contacto ")
  Cel=input("Numero de telefono ")
  Email=input("Correo electronico ")
  Contactos.append([Nom,Cel,Email])
  return
def Menu():
  print("""MENU
  1. Agregar
  2. Buscar por nombre
  3. Ver contactos
  4. Matar Contactos""")
  return
def Buscador():
  Busca=input("A quien buscamos pa? ")
  for c in Contactos:
    if Busca==c[0]:
      print(c)
      print("Encontrado")
def Matacontacto():
  Mata=input("A quien eliminamos pa? ")
  for c in Contactos:
    if Mata==c[0]:
      Contactos.remove(c)
      print("Eliminado")
    else:
      print("No encontrado")
  return
def Ver():
  print(Contactos)
  return
while True:
  Menu()
  Mov=input("Que hacemos pa? ")
  if Mov=="1":
    print("Agregar ")
    Agregar(a,b,c)
  elif Mov=="2":
    print("Buscar por nombre ")
    Buscador()
  elif Mov=="3":
    print("Ver contactos ")
    Ver()
  elif Mov=="4":
    print("Matar Contactos ")
    Matacontacto()
  else:
    print("Opcion invalida")

from random import shuffle
Corazones = "Corazones"
Diamantes = "Diamantes"
Treboles = "Treboles"
picas = "Picas"
J = "J"
Q = "Q"
K = "K"
A = "A"
Cartas=[[A,Corazones],[2,Corazones],[3,Corazones],[4,Corazones],[5,Corazones],[6,Corazones],[7,Corazones],[8,Corazones],[9,Corazones],[J,Corazones],[Q,Corazones],[K,Corazones],[A,Diamantes],[2,Diamantes],[3,Diamantes],[4,Diamantes],[5,Diamantes],[6,Diamantes],[7,Diamantes],[8,Diamantes],[9,Diamantes],[J,Diamantes],[Q,Diamantes],[K,Diamantes],[A,Treboles],[2,Treboles],[3,Treboles],[4,Treboles],[5,Treboles],[6,Treboles],[7,Treboles],[8,Treboles],[9,Treboles],[J,Treboles],[Q,Treboles],[K,Treboles],[A,Picas],[2,Picas],[3,Picas],[4,Picas],[5,Picas],[6,Picas],[7,Picas],[8,Picas],[9,Picas],[J,Picas],[Q,Picas],[K,picas]]
Mano1=[]
Mano2=[]
Mazo=[]
shuffle(Cartas)
Mano1=Cartas[0:4]
Mano2=Cartas[4:8]
print(Mano1)
print(Mano2)

from random import shuffle
Palo=["Corazones","Diamantes","Treboles","Picas"]
Cartas=["A","2","3","4","5","6","7","8","9","J","Q","K"]
Mazo=[]
for c in Palo:
  for a in Cartas:
    Mazo.append(a+"."+c)
shuffle(Mazo)
Mano1=Mazo[0:4]
Mano2=Mazo[4:8]
print(Mano1)
print(Mano2)

from IPython.display import clear_output
print("Hola")
print("Hola")
print("Hola")
print("Hola")
print("Hola")
input("Presiona enter para continuar")
clear_output()
print("Hola")
print("Hola")
print("Hola")
print("Hola")
print("Hola")

print("     _▲_")
print("      ☺      ")
print("     /|\\╔═     ")
print("     / \     ")
print("           ")

from IPython.display import clear_output
Register=[]
a=0
b=0
c=0
d=0

def Agregar(Nom,Cantidad,Precio):
  Nom=input("Nombre del producto ")
  Cantidad=int(input("Cantidad "))
  Precio=Cantidad*int(input("Precio Unidad"))
  Register.append([Nom,Cantidad,Precio])
  return
def Registro():
  print(Register)
  return
def Ventas(d):
  d
  for i in Register:
    d+=i[1]
  return d
def Menu():
  print("""MENU
  1. Agregar
  2. Ver Registro
  3. Ventas hoy""")
  return
while True:
  clear_output()
  Menu()
  Mov=input("Que hacemos pa? ")
  if Mov=="1":
    print("Agregar ")
    Agregar(a,b,c)
  elif Mov=="2":
    print("Ver Registro ")
    Registro()
    input("Presiona enter para continuar")
  elif Mov=="3":
    print("Ventas hoy ")
    d = Ventas(d)
    print("Vendimos",d)
    input("Presiona enter para continuar")
  else:
    print("Opcion invalida")

def suma(): #Como usar for doble y como sumar matrices
  Matriz1=[[1,2,3],[4,5,6],[7,8,9]]
  Matriz2=[[1,2,3],[4,5,6],[7,8,9]]
  Matriz3=[]
  for x in range(3):
    Matriz3.append([])
    for y in range(3):
      Matriz3[x].append(Matriz1[x][y]+Matriz2[x][y])
  print(Matriz3)
suma()

def flipin(): #
  Matriz1=[[1,2,3],[4,5,6],[7,8,9]]
  Matriz3=[]
  for x in range(3):
    Matriz3.append([])
    for y in range(3):
      Matriz3[x].append(Matriz1[y][x]) #Access the element at row y and column x of Matriz1
  print(Matriz3)
flipin()

def pablo():
  print("     _▲_")
  print("      ☺      ")
  print("     /|\\╔═     ")
  print("     / \     ")
def pedro():
  print("     _-_")
  print("      ☺      ")
  print("     /|\\     ")
  print("     / \     ")

personaje_seleccionado = input("¿Qué personaje quieres? (pablo o pedro): ")

def personaje():
  global personaje_seleccionado
  if personaje_seleccionado == "pablo":
    pablo()
  elif personaje_seleccionado == "pedro":
    pedro()
  else:
    print("Personaje no válido")

personaje()

print("""
___________                        _________                      __  .__    .__
\__    ___/__.__.______   ____    /   _____/ ____   _____   _____/  |_|  |__ |__| ____    ____
  |    | <   |  |\____ \_/ __ \   \_____  \ /  _ \ /     \_/ __ \   __\  |  \|  |/    \  / ___\
  |    |  \___  ||  |_> >  ___/   /        (  <_> )  Y Y  \  ___/|  | |   Y  \  |   |  \/ /_/  >
  |____|  / ____||   __/ \___  > /_______  /\____/|__|_|  /\___  >__| |___|  /__|___|  /\___  /
          \/     |__|        \/          \/             \/     \/          \/        \//_____/   """)

def suma(): #Como usar for doble y como sumar matrices
  Matriz1=[[1,2,3],[4,5,6],[7,8,9]]
  Matriz2=[[1,2,3],[4,5,6],[7,8,9]]
  Matriz3=[]
  Sum=0
  for x in range(3):
    Matriz3.append([])
    for y in range(3):
      Matriz3[x].append(Matriz1[x][y]*Matriz2[y][x])
  for x in range(3):
    for y in range(3):
      Sum+=(Matriz3[x][y])
  print(Matriz3)
  print(Sum)
suma()

def contar_caracteres():
    texto_ingresado = "Hola, mundo!"
    diccionario = {}
    for b in texto_ingresado:
        if b in diccionario:
            diccionario[b] += 1
        else:
            diccionario[b] = 1
    return diccionario


diccionario = contar_caracteres()
print(diccionario)

def identificador():
  Identidad = {}
  a = input("Dime tu nombre: ")
  b = input("Dime tu edad: ")
  c = input("Dime tu direccion: ")
  d = input("Dime tu telefono: ")
  persona={"nombre":a,"edad":b,"direccion":c,"telefono":d}
  print(persona["nombre"], "tiene", persona["edad"], "años, vive en", persona["direccion"], "y su numero es", persona["telefono"])

identificador()

Clientes={}
def registrar1():
  Nombre=input("Nombre: ")
  Direccion=input("Direccion: ")
  Correo=input("Correo: ")
  Preferente=input("Preferente: ")
  return {1:Nombre,2:Direccion,3:Correo,4:Preferente}

def registrar2(x):
  global Clientes
  Clave=input("Cedula: ")
  Clientes[Clave] = x
  return

def Eliminar():
  Clave = input("Cedula del bendecido: ")
  if Clave == Clientes:
    del Clientes[Clave]
  else:
    print("No encontrado")
  return

def Buscar():
  Clave = input("Cedula del deudor: ")
  if Clave == Clientes:
    print(Clientes[Clave])
  else:
    print("No encontrado")
  return

def Lista():
  print(Clientes)
  return


def Menu():
  print("""
        Bienvenido Proletario!
        1. Agregar alma
        2. Liberar perjudicado
        3. Buscar deudor
        4. Lista de ingresos
        5. Lista de esbirros
        6. Hasta pronto""")
  while True:
    Mov=input("Que fechoria haremos? ")
    if Mov=="1":
      print("Agregar alma")
      registrar1()
      A = registrar1()
      registrar2(A)
    if Mov=="2":
      print("Liberar perjudicado")
      Eliminar()
    if Mov=="3":
      print("Buscar deudor")
      Buscar()
    if Mov=="4":
      print("Lista de ingresos")
      Lista()
    if Mov=="5":
      print("Lista de esbirros")
    if Mov=="6":
      print("Hasta pronto")
      break
    else:
      print("No encontrado")

Menu()

W=set([1,2,3])
W.remove(11)
print(W)

def Subconjunter():
  si=set([1,2,3,4,5])
  sa=set([2,3,4])
  set3 = si.intersection(sa)
  if set3==sa:
    print("Si es subconjunto")
  else:
    print("No es subconjunto")
Subconjunter()
#

def imparizador():
  si=set([1,2,3,4,5,6,7,8,9,0])
  sa=set([])
  for i in si:
    if i%2==0:
      sa.add(i)
  print(sa)
imparizador()

def menu1():
  Sa=set([])
  Mov=print("""
        1. Introduzca el nombre del niño de primaria
        2. Introduzca XXX para terminar""")
  while True:
    PO=input("Que hacemos pa? ")
    if PO=="XXX":
      print("Terminado")
      break
    else:
      Sa.add(PO)
  return Sa
def menu2():
  Sa=set([])
  Mov=print("""
        1. Introduzca el nombre del niño de secundaria
        2. Introduzca XXX para terminar""")
  while True:
    PO=input("Que hacemos pa? ")
    if PO=="XXX":
      print("Terminado")
      break
    else:
      Sa.add(PO)
  return Sa
Primaria=menu1()
Secundaria=menu2()
A=Primaria.union(Secundaria)
B=Primaria.intersection(Secundaria)
C=Primaria.difference(Secundaria)
print(A)
print(B)
print(C)

import csv