# -*- coding: utf-8 -*-
"""pythonConditionalsLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4UMY5Yen30jsOJ8_jHKGky2wY2FMsaV
"""

# Inicio estableciendo las variables mas importantes con las que va a trabajar el programa.
A=0
descuento=0
Pc=0
# Pregunto al usuario por algunos datos con los que sumare determinados puntos dependiendo de los parametros dados.
PI=int(input("Ingrese el puntaje del ICFES: "))
if PI<50:
  print("No estas admitido")
  exit() #En caso de sacar menos de 50 el programa finaliza
elif (PI>=100): #Una formula que permite acortar el codigo reduciendo varios "elif"
  A+=6
else:
  A= (PI-50)//10+1
#En caso de preguntas con strings, solo necesito aclarar la respuesta que sume puntos.
C=str(input("Colegio publico o privado: "))
if C=="publico":
  A+=1
  descuento+=0.02
else:
  A+=0
  descuento+=0
E=input("Estrato: ")
if E=="1":
  A+=6
  descuento+=0.10
elif E=="2":
  A+=5
  descuento+=0.09
elif E=="3":
  A+=4
  descuento+=0.08
elif E=="4":
  A+=3
  descuento+=0.07
elif E=="5" or "6":
  A+=3
  descuento+=0.02
else:
  A+=0
  descuento=0
  print("No es un estrato valido")
M=str(input("Situacion militar: ")) #Chayane es menor por lo que se toma como no definida, de igual forma no suma.
if M=="Definida" or "definida":
  A+=1
else:
  A+=0
Etn=str(input("Pertences a una comunidad etnica o minoria?: "))
if Etn=="Si" or "si":
  A+=1
  descuento+=0.15
else:
  A+=0
if A>=4:
  print("Estas admitido")
else:
  print("No estas admitido")
  exit()
#introduzco una sola variable que tomara diferentes precios dependiendo la respuesta para acortar el numero de variables que hay.
F=str(input("Cual facultad quieres ingresar?: "))
if F=="Salud":
  Pc+=10000000
elif F=="Ingenieria":
  Pc+=8000000
elif F=="Artes":
  Pc+=6000000
else:
  print("No valido")
  exit()
print(A)
z=1-descuento
H=descuento*100
print(z)
x=Pc*z
print("Tienes una beca del", str(H) + "%")
print("Debes pagar", x)