# -*- coding: utf-8 -*-
"""pythonMathLearning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wncUjQrbSJiUosRwO_0rIc6GMf208Wuc
"""

a=float(input("cantidad a invertir"))
b=float(input("interes anual"))
c=int(input("numero de años"))
print(float(a*(b/100+1)**c))

a=float(input("# PAYASOS VENDIDOS "))
b=float(input("# MUÑECAS VENDIDAS "))
str(print("Peso payaso en KG: ",a*112/1000))
str(print("Peso muñeca en KG: ",a*75/1000))
c=float(a*112/1000)
d=float(a*75/1000)
print("Peso total en KG: " + str(c+d))

a=float(input("Cantidad de dinero "))
b=round(float(a*1.04),2)
c=round(float(a*1.04**2),2)
d=round(float(a*1.04**3),2)
print("En 1 año: " + str(b),"COP")
print("En 2 años: " + str(c),"COP")
print("En 3 años: " + str(d),"COP")

a=int(input("Numero de panes vencidos vendidos"))
print("Precio del pan: 3000","Descuento por vencimiento: 40%")
print("Precio del pan vencido vendido: ",str(a*3000*0.6),"COP")